---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wty.
--- DateTime: 2025/1/16 22:19
---
Global = {}

---@type UGameInstance
Global.g_gameInstance = nil;
---@type LuaMgr
Global.g_luaMgr = nil;

---@type ResMgr
Global.g_resMgr = nil;
---@type string
Global._LuaSrcPath = "";
---@type string
Global._ProjectPersistentDownloadDir = "";
---@type boolean
Global.bServer = false;

---@type Ticker
Global.g_Ticker = nil;

---@type BattleUtils
Global.g_BattleUtils = nil;
---@type EventMgr
Global.g_event = nil

Global.g_level = nil

--Worlds
---@type World @大厅
Global.HallWorld = nil
---@type World @战斗
Global.BattleWorld = nil
---@type World @展示界面
Global.UIWorld = nil
---@type boolean
Global.PreUser = nil;
---@type boolean
Global.SdkIsSandbox = false;
Global.Json = require("Json.json")
