require "UnLua"
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wutianyi.
--- DateTime: 2025/1/15 10:41
---


local LuaMgr = Class()

---@private
function LuaMgr:Init()
    local luaPath = UE4.TArray("");
    luaPath:Add("Client/")
    luaPath:Add("Client/Cfg/")
    luaPath:Add("Client/Msg/Gs/")
    luaPath:Add("Client/Msg/As/")
    luaPath:Add("Client/Msg/Gate/")
    luaPath:Add("Share/")
    self:SetLuaSearchPathAndOcPath(luaPath, "Cfg/");
    self:InitRequirePath()

    require("HashSet")
    require("HashMap")
    require("ArrayList")

    Global.g_luaMgr = self;
    Global.g_gameInstance = self:GetGameInstance();
    Global.g_resMgr = self:GetResMgr();
    Global._ProjectPersistentDownloadDir = self:GetPersistentDownloadDir();
    --Global.g_FPSMgr = Global.g_luaMgr:GetFPSManager();

    require("Utils")
    require("Event.EventUtils")
    self:RequireAllCfgs()
    self:LoadLuaFileOnInit()
    Global.g_resMgr:Init();
end

---@private
function LuaMgr:Start()

    UIWidgetMgr.Init("/Game/UI/UI_PC/", "WBP_Rotating_loading_p")
    --UIWidgetMgr.Prepare("WBP_BattleLoading", true)
    --UIWidgetMgr.Show("WBP_BattleLoading")
end

function LuaMgr:InitRequirePath()
    local luaSrcPath, luarelativepath = self:GetLuaSrcPath()
    print("luaSrcPath is ", luarelativepath, luaSrcPath)
    package.path = string.format("%sClient/?.lua;%sShare/?.lua;%s", luaSrcPath, luaSrcPath, package.path)

    require("Global")
    Global._LuaSrcPath = luarelativepath;
end

function LuaMgr:RequireAllCfgs()
    local luaSrcPath = self:GetLuaSrcPath()
    local oldPath = package.path
    package.path = string.format("%sClient/Cfg/?.lua;", luaSrcPath) .. oldPath
    require("ALLCFGS")
    package.path = oldPath
end

function LuaMgr:Shutdown()
end

function LuaMgr:LoadLuaFileOnInit()
    require("ResMgr.ClientResMgr")
    require("UI.UIWidgetMgr");
end

return LuaMgr
