require "UnLua"
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wutianyi.
--- DateTime: 2025/1/15 10:41
---


local LuaMgr = Class()


---@private
function LuaMgr:Init()

end

---@private
function LuaMgr:Start()

    print("!!!!!!!!!!!")
    local luaPath = UE4.TArray("");
    luaPath:Add("Client/")
    luaPath:Add("Client/Cfg/")
    self:SetLuaSearchPathAndOcPath(luaPath, "Cfg/");
    self:InitRequirePath()

    require("HashSet")
    require("HashMap")
    require("ArrayList")
    
    Global.g_luaMgr = self;
    --Global.g_gameInstance = self:GetGameInstance();
    --Global.g_resMgr = self:GetResMgr();
    --Global._ProjectPersistentDownloadDir = self:GetPersistentDownloadDir();
    --Global.g_FPSMgr = Global.g_luaMgr:GetFPSManager();
    require("Utils")
    self:RequireAllCfgs()
end


function LuaMgr:InitRequirePath()
    local luaSrcPath , luarelativepath   = self:GetLuaSrcPath()
    print("luaSrcPath is ", luarelativepath, luaSrcPath)
    package.path = string.format("%sClient/?.lua;%sShare/?.lua;%s", luaSrcPath, luaSrcPath, package.path)

    require("Global")
    Global._LuaSrcPath = luarelativepath;
end

function LuaMgr:RequireAllCfgs()
    local luaSrcPath = self:GetLuaSrcPath()
    local oldPath = package.path
    package.path = string.format("%sClient/Cfg/?.lua;", luaSrcPath) .. oldPath
    require("ALLCFGS")
    package.path = oldPath
end

return LuaMgr
