require "UnLua"
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wutianyi.
--- DateTime: 2025/1/15 10:41
---


local LuaMgr = Class()

---@private
function LuaMgr:Init()

    print("!!!!!!!!!!!")
end

return LuaMgr
